# Generated by Django 5.1 on 2024-08-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_patients', models.IntegerField(default=0)),
                ('active_patients', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('appointments_completed', models.IntegerField(default=0)),
                ('appointments_canceled', models.IntegerField(default=0)),
                ('average_patient_recovery_time', models.DurationField(blank=True, null=True)),
                ('common_conditions', models.TextField(blank=True, null=True)),
                ('show_upcoming_appointments', models.BooleanField(default=True)),
                ('show_patient_summary', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
