# Generated by Django 5.1 on 2024-08-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0003_patientsprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='patients_treated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='upcoming_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
