# Generated by Django 5.1 on 2024-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
