# Generated by Django 5.1 on 2024-09-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0007_doctorprofile_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
