# Generated by Django 5.1 on 2024-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0008_alter_doctorprofile_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
