# Generated by Django 5.1 on 2024-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0009_message_encrypted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
    ]
