# Generated by Django 5.1 on 2024-09-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0010_doctorprofile_is_available_doctorprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='speciality',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_doctor',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
