# Generated by Django 5.1.1 on 2024-09-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0014_alter_patientsprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
