# Generated by Django 5.1.1 on 2024-09-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilink', '0017_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
